import type { InsertCityCandidate } from "../shared/schema.js";

const images = {
  delhi:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/delhi.webp",
  noida:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/noida.webp",
  jaipur:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/jaipur.webp",
  mussoorie:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/mussoorie.webp",
  goa:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/goa.webp",
  cafe:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/cafe.webp",
  market:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/market.webp",
  sunset:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/sunset.webp",
};

export const DEFAULT_CITY_CANDIDATES: InsertCityCandidate[] = [
  {
    city: "Delhi",
    candidateId: "delhi-lodhi-garden",
    title: "Lodhi Garden",
    category: "scenic",
    location: "Lodhi Road, New Delhi",
    image: images.delhi,
    price: "Free",
    rating: "4.6",
    duration: "60-90 minutes",
    tags: ["outdoors", "walk", "low-cost"],
    metadata: { bestFor: ["evening", "photos"], source: "curated" },
    sortOrder: 1,
  },
  {
    city: "Delhi",
    candidateId: "delhi-connaught-place",
    title: "Connaught Place",
    category: "food",
    location: "Connaught Place, New Delhi",
    image: images.cafe,
    price: "INR INR",
    rating: "4.5",
    duration: "2 hours",
    tags: ["central", "food", "shopping"],
    metadata: { bestFor: ["mixed groups", "easy transit"], source: "curated" },
    sortOrder: 2,
  },
  {
    city: "Noida",
    candidateId: "noida-sector-18",
    title: "Sector 18 Cafe Cluster",
    category: "cafe",
    location: "Sector 18, Noida",
    image: images.cafe,
    price: "INR INR",
    rating: "4.4",
    duration: "90 minutes",
    tags: ["cafe", "metro", "weekday"],
    metadata: { bestFor: ["quick catchups"], source: "curated" },
    sortOrder: 1,
  },
  {
    city: "Noida",
    candidateId: "noida-gardens-galleria",
    title: "Gardens Galleria",
    category: "food",
    location: "Sector 38, Noida",
    image: images.noida,
    price: "INR INR INR",
    rating: "4.3",
    duration: "2-3 hours",
    tags: ["dinner", "nightlife", "group-friendly"],
    metadata: { bestFor: ["evening plans"], source: "curated" },
    sortOrder: 2,
  },
  {
    city: "Jaipur",
    candidateId: "jaipur-bapu-bazaar",
    title: "Bapu Bazaar",
    category: "shopping",
    location: "Bapu Bazaar, Jaipur",
    image: images.market,
    price: "INR INR",
    rating: "4.4",
    duration: "90 minutes",
    tags: ["market", "souvenirs", "walk"],
    metadata: { bestFor: ["browsing", "local finds"], source: "curated" },
    sortOrder: 1,
  },
  {
    city: "Jaipur",
    candidateId: "jaipur-hawa-mahal",
    title: "Hawa Mahal",
    category: "landmark",
    location: "Hawa Mahal Road, Jaipur",
    image: images.jaipur,
    price: "INR",
    rating: "4.5",
    duration: "45-60 minutes",
    tags: ["photos", "heritage", "landmark"],
    metadata: { bestFor: ["first-time visitors"], source: "curated" },
    sortOrder: 2,
  },
  {
    city: "Mussoorie",
    candidateId: "mussoorie-landour",
    title: "Landour Walk",
    category: "scenic",
    location: "Landour, Mussoorie",
    image: images.mussoorie,
    price: "Free",
    rating: "4.8",
    duration: "2 hours",
    tags: ["walk", "views", "slow"],
    metadata: { bestFor: ["calm plans"], source: "curated" },
    sortOrder: 1,
  },
  {
    city: "Goa",
    candidateId: "goa-candolim-beach",
    title: "Candolim Beach",
    category: "beach",
    location: "Candolim, Goa",
    image: images.goa,
    price: "Free",
    rating: "4.5",
    duration: "2-3 hours",
    tags: ["beach", "relaxed", "daytime"],
    metadata: { bestFor: ["slow starts", "groups"], source: "curated" },
    sortOrder: 1,
  },
  {
    city: "Goa",
    candidateId: "goa-fort-aguada",
    title: "Fort Aguada",
    category: "landmark",
    location: "Sinquerim, Goa",
    image: images.sunset,
    price: "INR",
    rating: "4.5",
    duration: "60-90 minutes",
    tags: ["views", "history", "sunset"],
    metadata: { bestFor: ["golden hour"], source: "curated" },
    sortOrder: 2,
  },
];
