import type { InsertPrebuiltRoute } from "../shared/schema.js";

const images = {
  delhi:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/delhi.webp",
  noida:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/noida.webp",
  jaipur:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/jaipur.webp",
  mussoorie:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/mussoorie.webp",
  goa:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/goa.webp",
  cafe:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/cafe.webp",
  market:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/market.webp",
  sunset:
    "https://rdmypruvhkqvfdjfohpk.supabase.co/storage/v1/object/public/carousel-images/sunset.webp",
};



export const DEFAULT_PREBUILT_ROUTES: InsertPrebuiltRoute[] = [
  {
    slug: "delhi-food-walk",
    city: "Delhi",
    mood: "Best for food stops",
    stops: "4 stops",
    accent: "bg-[#ff385c]",
    image: images.delhi,
    tagline: "Heritage courtyards and late-night food trails",
    sortOrder: 1,
    itinerary: {
      title: "Delhi Food Walk With Friends",
      description: "A ready-to-send Delhi plan with heritage streets, easy bites, and a relaxed evening stop.",
      location: "Delhi",
      activities: [
        {
          id: "delhi-1",
          time: "10:00 AM",
          title: "Start at India Gate Lawns",
          description: "Meet somewhere simple, take a few photos, and ease into the day before the food stops begin.",
          location: "India Gate, New Delhi",
          image: images.delhi,
          price: "Free",
          rating: "4.6",
          timeOfDay: "morning",
          type: "landmark",
        },
        {
          id: "delhi-2",
          time: "12:00 PM",
          title: "Lunch Around Connaught Place",
          description: "Pick a central lunch spot so everyone can reach easily and the group has plenty of options.",
          location: "Connaught Place, New Delhi",
          image: images.cafe,
          price: "₹₹",
          rating: "4.5",
          timeOfDay: "afternoon",
          type: "food",
        },
        {
          id: "delhi-3",
          time: "3:00 PM",
          title: "Old Delhi Snack Trail",
          description: "Walk through a classic food lane and split a few things instead of committing to one heavy stop.",
          location: "Chandni Chowk, Delhi",
          image: images.market,
          price: "₹",
          rating: "4.7",
          timeOfDay: "afternoon",
          type: "food",
        },
        {
          id: "delhi-4",
          time: "6:30 PM",
          title: "Wind Down at Lodhi Garden",
          description: "End with a calm walk and space to sit before everyone heads home.",
          location: "Lodhi Garden, New Delhi",
          image: images.delhi,
          price: "Free",
          rating: "4.6",
          timeOfDay: "evening",
          type: "scenic",
        },
      ],
      recommendations: [
        {
          id: "delhi-rec-1",
          title: "Delhi Coffee Catch-up",
          description: "A shorter cafe-first plan for when the group wants something easy.",
          image: images.cafe,
          rating: "4.5",
          duration: "2-3 hours",
        },
      ],
    },
  },
  {
    slug: "noida-cafe-day",
    city: "Noida",
    mood: "Best for cafe time",
    stops: "3 stops",
    accent: "bg-[#56cfb8]",
    image: images.noida,
    tagline: "Sleek cafes, creative corners, and quick escapes",
    sortOrder: 2,
    itinerary: {
      title: "Noida Cafe And Arcade Day",
      description: "A low-effort Noida route with coffee, a fun indoor stop, and dinner close by.",
      location: "Noida",
      activities: [
        {
          id: "noida-1",
          time: "11:00 AM",
          title: "Coffee Meet-up in Sector 18",
          description: "Start at a familiar cafe zone so late arrivals can join without derailing the plan.",
          location: "Sector 18, Noida",
          image: images.cafe,
          price: "₹₹",
          rating: "4.4",
          timeOfDay: "morning",
          type: "cafe",
        },
        {
          id: "noida-2",
          time: "2:00 PM",
          title: "Games and Shopping Break",
          description: "Keep the afternoon flexible with a mall stop where the group can split and regroup easily.",
          location: "DLF Mall of India, Noida",
          image: images.noida,
          price: "₹₹",
          rating: "4.6",
          timeOfDay: "afternoon",
          type: "activity",
        },
        {
          id: "noida-3",
          time: "7:00 PM",
          title: "Dinner Near Gardens Galleria",
          description: "End somewhere lively with enough food choices for different moods.",
          location: "Gardens Galleria, Noida",
          image: images.noida,
          price: "₹₹₹",
          rating: "4.3",
          timeOfDay: "evening",
          type: "food",
        },
      ],
      recommendations: [
        {
          id: "noida-rec-1",
          title: "Noida Quick Coffee Plan",
          description: "A compact route for a weekday catch-up.",
          image: images.cafe,
          rating: "4.4",
          duration: "2 hours",
        },
      ],
    },
  },
  {
    slug: "jaipur-bazaar-day",
    city: "Jaipur",
    mood: "Best for browsing",
    stops: "5 stops",
    accent: "bg-[#ffd55a]",
    image: images.jaipur,
    tagline: "Palace pink mornings and bazaars worth wandering",
    sortOrder: 3,
    itinerary: {
      title: "Jaipur Bazaar And Fort Day",
      description: "A colorful Jaipur route with a palace stop, local shopping, snacks, and a sunset finish.",
      location: "Jaipur",
      activities: [
        {
          id: "jaipur-1",
          time: "9:30 AM",
          title: "Amber Fort Morning",
          description: "Start early while the light is good and the group still has energy.",
          location: "Amber Fort, Jaipur",
          image: images.jaipur,
          price: "₹₹",
          rating: "4.7",
          timeOfDay: "morning",
          type: "historical",
        },
        {
          id: "jaipur-2",
          time: "12:30 PM",
          title: "Lunch Near C-Scheme",
          description: "Reset with a comfortable lunch before heading into the busier market stretch.",
          location: "C-Scheme, Jaipur",
          image: images.cafe,
          price: "₹₹",
          rating: "4.5",
          timeOfDay: "afternoon",
          type: "food",
        },
        {
          id: "jaipur-3",
          time: "2:30 PM",
          title: "Bapu Bazaar Browsing",
          description: "Make time for souvenirs, fabrics, and wandering without rushing the group.",
          location: "Bapu Bazaar, Jaipur",
          image: images.market,
          price: "₹₹",
          rating: "4.4",
          timeOfDay: "afternoon",
          type: "shopping",
        },
        {
          id: "jaipur-4",
          time: "5:00 PM",
          title: "Hawa Mahal Photo Stop",
          description: "Add one iconic stop before evening so the day has a proper Jaipur memory.",
          location: "Hawa Mahal, Jaipur",
          image: images.jaipur,
          price: "₹",
          rating: "4.5",
          timeOfDay: "evening",
          type: "landmark",
        },
        {
          id: "jaipur-5",
          time: "7:30 PM",
          title: "Rooftop Dinner",
          description: "Close the route somewhere relaxed with city views and enough time to linger.",
          location: "MI Road, Jaipur",
          image: images.jaipur,
          price: "₹₹₹",
          rating: "4.5",
          timeOfDay: "evening",
          type: "food",
        },
      ],
      recommendations: [
        {
          id: "jaipur-rec-1",
          title: "Jaipur Photo Walk",
          description: "A shorter route for landmarks, pictures, and snacks.",
          image: images.jaipur,
          rating: "4.6",
          duration: "4 hours",
        },
      ],
    },
  },
  {
    slug: "mussoorie-slow-view-day",
    city: "Mussoorie",
    mood: "Best for a slow day",
    stops: "3 stops",
    accent: "bg-[#7c6df2]",
    image: images.mussoorie,
    tagline: "Misty hills, postcard views, and slow walks",
    sortOrder: 4,
    itinerary: {
      title: "Mussoorie Slow View Day",
      description: "A softer hill-station plan with views, snacks, and enough breathing room between stops.",
      location: "Mussoorie",
      activities: [
        {
          id: "mussoorie-1",
          time: "10:30 AM",
          title: "Landour Walk",
          description: "Start with a quiet walk, mountain air, and a pace that feels like a break.",
          location: "Landour, Mussoorie",
          image: images.mussoorie,
          price: "Free",
          rating: "4.8",
          timeOfDay: "morning",
          type: "scenic",
        },
        {
          id: "mussoorie-2",
          time: "1:00 PM",
          title: "Lunch With A View",
          description: "Pick a warm cafe or hillside restaurant and let the group slow down.",
          location: "Mall Road, Mussoorie",
          image: images.cafe,
          price: "₹₹",
          rating: "4.5",
          timeOfDay: "afternoon",
          type: "cafe",
        },
        {
          id: "mussoorie-3",
          time: "5:30 PM",
          title: "Sunset At Camel's Back Road",
          description: "End with an easy sunset walk instead of squeezing in one more rushed stop.",
          location: "Camel's Back Road, Mussoorie",
          image: images.mussoorie,
          price: "Free",
          rating: "4.6",
          timeOfDay: "evening",
          type: "scenic",
        },
      ],
      recommendations: [
        {
          id: "mussoorie-rec-1",
          title: "Mussoorie Cafe Afternoon",
          description: "A smaller plan for coffee, views, and an unhurried walk.",
          image: images.cafe,
          rating: "4.5",
          duration: "3 hours",
        },
      ],
    },
  },
  {
    slug: "goa-sunset-plan",
    city: "Goa",
    mood: "Best for sunset plans",
    stops: "4 stops",
    accent: "bg-[#ff9f6e]",
    image: images.goa,
    tagline: "Sun-faded beaches, shacks, and golden hour rides",
    sortOrder: 5,
    itinerary: {
      title: "Goa Beach And Sunset Plan",
      description: "A beach-first Goa route with a lazy lunch, golden-hour stop, and dinner near the water.",
      location: "Goa",
      activities: [
        {
          id: "goa-1",
          time: "10:30 AM",
          title: "Beach Start At Candolim",
          description: "Begin with an easy beach stop where the group can settle in without a strict agenda.",
          location: "Candolim Beach, Goa",
          image: images.goa,
          price: "Free",
          rating: "4.5",
          timeOfDay: "morning",
          type: "beach",
        },
        {
          id: "goa-2",
          time: "1:30 PM",
          title: "Shack Lunch",
          description: "Keep lunch casual, close to the beach, and simple for everyone to enjoy.",
          location: "Calangute, Goa",
          image: images.sunset,
          price: "₹₹",
          rating: "4.4",
          timeOfDay: "afternoon",
          type: "food",
        },
        {
          id: "goa-3",
          time: "4:30 PM",
          title: "Fort Aguada View Stop",
          description: "Add one scenic stop before sunset so the day has a little exploring in it.",
          location: "Fort Aguada, Goa",
          image: images.goa,
          price: "₹",
          rating: "4.5",
          timeOfDay: "afternoon",
          type: "landmark",
        },
        {
          id: "goa-4",
          time: "7:00 PM",
          title: "Dinner Near Anjuna",
          description: "Finish somewhere lively enough for dinner, music, and one last round of photos.",
          location: "Anjuna, Goa",
          image: images.sunset,
          price: "₹₹₹",
          rating: "4.5",
          timeOfDay: "evening",
          type: "food",
        },
      ],
      recommendations: [
        {
          id: "goa-rec-1",
          title: "Goa Slow Beach Day",
          description: "A softer version with fewer stops and more beach time.",
          image: images.goa,
          rating: "4.5",
          duration: "Half day",
        },
      ],
    },
  },
];
